In [1]:
import pandas as pd
import numpy as np
import tqdm
import warnings
import matplotlib.pyplot as plt

pd.set_option("max_rows", 200)
pd.set_option("max_columns", 50)

%matplotlib inline

In [2]:


data_types_dict = {
    'row_id': 'int64',
    'timestamp': 'int64',
    'user_id': 'int32',
    'content_id': 'int16',
    'content_type_id': 'int8',
    'task_container_id': 'int16',
    'user_answer': 'int8',
    'answered_correctly': 'int8',
}


df = pd.read_pickle("../input/riiid-test-answer-prediction/split10/train_0.pickle")

In [3]:
import sys
sys.path.append("../")
# df = pd.read_pickle("../input/riiid-test-answer-prediction/split10/train_0.pickle")
df = df.sort_values(["user_id", "timestamp"])
# large_user_id = df["user_id"].value_counts()
# large_user_id = large_user_id[large_user_id > 1000] 
# df = df[df["user_id"].isin(large_user_id.index)]
# df = df[df["answered_correctly"] != -1]

In [4]:
df["answered_correctly"] = df["answered_correctly"].replace(-1, np.nan)

In [5]:
tags = df["tags"].str.split(" ", n=10, expand=True)

In [17]:
tag = df["tags"].str.split(" ", n=10, expand=True)
tag.columns = [f"tags{i}" for i in range(1, len(tag.columns) + 1)]


for col in ["tags1", "tags2", "tags3", "tags4", "tags5", "tags6"]:
    tag[col] = pd.to_numeric(tag[col], errors='coerce').fillna(-1).astype("int16")

In [20]:
for t in tqdm.tqdm(tag["tags1"].drop_duplicates().values):
    df[f"tag_{t}"] = (tag == t).sum(axis=1).astype("int16")

100%|██████████| 118/118 [01:27<00:00,  1.35it/s]


In [22]:
cols = [f"tag_{x}" for x in tag["tags1"].drop_duplicates().values]

In [23]:
cols

['tag_131',
 'tag_10',
 'tag_9',
 'tag_143',
 'tag_157',
 'tag_136',
 'tag_74',
 'tag_82',
 'tag_161',
 'tag_80',
 'tag_123',
 'tag_133',
 'tag_23',
 'tag_151',
 'tag_79',
 'tag_73',
 'tag_96',
 'tag_65',
 'tag_27',
 'tag_50',
 'tag_97',
 'tag_115',
 'tag_134',
 'tag_1',
 'tag_91',
 'tag_109',
 'tag_125',
 'tag_132',
 'tag_69',
 'tag_129',
 'tag_17',
 'tag_62',
 'tag_137',
 'tag_55',
 'tag_48',
 'tag_28',
 'tag_53',
 'tag_156',
 'tag_60',
 'tag_127',
 'tag_49',
 'tag_75',
 'tag_15',
 'tag_51',
 'tag_90',
 'tag_138',
 'tag_7',
 'tag_173',
 'tag_177',
 'tag_58',
 'tag_147',
 'tag_31',
 'tag_45',
 'tag_61',
 'tag_179',
 'tag_47',
 'tag_95',
 'tag_24',
 'tag_54',
 'tag_44',
 'tag_152',
 'tag_175',
 'tag_116',
 'tag_181',
 'tag_180',
 'tag_170',
 'tag_85',
 'tag_8',
 'tag_26',
 'tag_155',
 'tag_2',
 'tag_174',
 'tag_52',
 'tag_33',
 'tag_106',
 'tag_113',
 'tag_14',
 'tag_128',
 'tag_43',
 'tag_89',
 'tag_-1',
 'tag_78',
 'tag_76',
 'tag_118',
 'tag_18',
 'tag_37',
 'tag_84',
 'tag_39',
 't

In [11]:
s = df[cols].sum().sort_values(ascending=False)

In [20]:
from sklearn.decomposition import PCA

In [29]:
tag["tags4"].drop_duplicates().sort_values().values

array([ -1,   0,  11,  22,  29,  35,  38,  63,  81,  87,  92, 102, 117,
       121, 122, 135, 139, 146, 154, 162, 165], dtype=int16)

In [28]:
tag["tags3"].drop_duplicates().sort_values().values

array([ -1,   0,   3,   6,  11,  16,  18,  20,  21,  29,  30,  32,  35,
        38,  39,  41,  42,  46,  50,  56,  59,  62,  69,  71,  76,  77,
        81,  87,  88,  92,  97, 100, 102, 105, 107, 114, 117, 118, 119,
       135, 138, 141, 142, 145, 146, 148, 154, 160, 162, 163, 176, 184,
       185, 186], dtype=int16)

In [27]:
tag["tags1"].drop_duplicates().sort_values().values

array([ -1,   1,   2,   4,   7,   8,   9,  10,  14,  15,  16,  17,  18,
        19,  23,  24,  25,  26,  27,  28,  31,  32,  33,  34,  37,  38,
        39,  41,  42,  43,  44,  45,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  57,  58,  60,  61,  62,  64,  65,  66,  69,  72,  73,
        74,  75,  76,  78,  79,  80,  82,  84,  85,  86,  89,  90,  91,
        95,  96,  97,  98, 100, 106, 108, 109, 112, 113, 115, 116, 117,
       118, 123, 124, 125, 127, 128, 129, 131, 132, 133, 134, 136, 137,
       138, 143, 145, 147, 148, 151, 152, 155, 156, 157, 159, 160, 161,
       166, 167, 168, 170, 172, 173, 174, 175, 177, 179, 180, 181, 182,
       184], dtype=int16)

In [26]:
tag["tags2"].drop_duplicates().sort_values().values

array([ -1,   0,   2,   5,  10,  12,  13,  16,  17,  18,  19,  20,  29,
        30,  32,  35,  36,  37,  38,  39,  40,  41,  42,  50,  56,  62,
        67,  68,  69,  70,  71,  76,  77,  81,  83,  84,  88,  90,  92,
        93,  94,  97,  99, 100, 101, 102, 103, 104, 105, 107, 110, 111,
       114, 117, 118, 119, 120, 126, 130, 131, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 148, 149, 150, 153, 155, 158, 160, 162, 163,
       164, 169, 171, 176, 178, 183, 184, 185, 187], dtype=int16)

In [16]:
df.iloc[tag[tag["tags2"] == -126].index]["tags"]

69                 131 130 38
76                 131 130 92
133            131 130 162 38
142               131 130 102
631        129 143 176 38 102
                  ...        
9639559                     1
9639768        143 114 38 102
9639777                   152
9640880         136 162 92 29
9640907             157 38 81
Name: tags, Length: 24104, dtype: object

In [31]:
tag["tags2"].astype("uint8")

0           93
1           94
2           10
3          140
4           92
          ... 
9837537    255
9837538    255
9837539    255
9837540    255
9837541    255
Name: tags2, Length: 10033866, dtype: uint8

In [ ]:
pca = PCA()

In [13]:
s[s>10**5]

tag_-1     36939817
tag_38      1657688
tag_143      720211
tag_136      502226
tag_131      443507
tag_62       332508
tag_73       324914
tag_53       296607
tag_74       288813
tag_82       278638
tag_27       255843
tag_10       254659
tag_1        240811
tag_155      228826
tag_106      218494
tag_96       208994
tag_137      205101
tag_8        201115
tag_90       193438
tag_100      174930
tag_2        172370
tag_97       171172
tag_157      154663
tag_32       143417
tag_55       137340
tag_69       131873
tag_138      130919
tag_148      126063
tag_41       124879
tag_79       121068
tag_42       108547
tag_173      107509
tag_118      102797
tag_98       102145
dtype: int64

In [21]:
df.groupby(["tag_38", "part"]).size()

tag_38  part
0       1        581676
        2        952121
        3        460487
        4        651753
        5       4182879
        6       1050297
        7        496965
1       1        175612
        2        950553
        3        387897
        4        143626
dtype: int64

In [22]:
df.groupby(["tag_143", "part"]).size()

tag_143  part
0        1        757288
         2       1182463
         3        848384
         4        795379
         5       4182879
         6       1050297
         7        496965
1        2        720211
dtype: int64

In [14]:
df.groupby("tag_38")["answered_correctly"].mean()

tag_38
0    0.643411
1    0.712293
Name: answered_correctly, dtype: float64

In [19]:
df.groupby("tag_78")["answered_correctly"].mean()

tag_78
0    0.655002
1    0.663080
Name: answered_correctly, dtype: float64